#!/usr/bin/env python

from os import listdir
from os.path import join
from glob import glob
import numpy as np
import sys
import getpass
import argparse

from k2crank.run_pipeline import run

def str2bool(v):
    '''
    see https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse
    '''
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')


parser = argparse.ArgumentParser(description="""
                read, reduce and detrend K2 photometry""",
                usage='use "%(prog)s --help" for more information',
                formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('--indir', help='path to fits file directory',
    type=str, default='./')
parser.add_argument('--outdir', help='output directory (default: output/)',
    type=str, default='output/')
parser.add_argument('--showfig', help='show all plots (default: True)',
    type=str2bool, default=True)

args = parser.parse_args()

inputpath = args.indir
outputpath = args.outdir
showfig = args.showfig


#initialize
print('-----------------------')
print('Checking raw data')
print('-----------------------\n')

# get all files in the folder, just grab the EPIC number of the filename
fitfiles = glob(join(inputpath,'*.fits'))
starnames = np.unique([f.split('/')[-1][4:13] for f in fitfiles])
i = 0

exc_list = []
while i < len(starnames):
  print('Now running stars, number ')
  print(str(i))

  try:
    run(starnames[i],outputpath=outputpath,inputpath=inputpath,makelightcurve=True, showfig=showfig)#,campaign=14)

  except Exception as inst:
    print inst
    exc_list.append(inst)
  i = i + 1

if exc_list:
  print('Module failed for some stars:')
  print(exc_list)

print('-----------------------')
print('          DONE')
print('-----------------------\n')
